name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    uses: origin-blocks/theme-workflows/.github/workflows/build-release.yml@v1
    with:
      theme-name: origin
      node-version: '18'
